### ISSUE TITLE
How to edit channel permissions?

### ISSUE THREAD

**Issue by 5HT2** [Tea-Ayataka/Kordis#11]
I apologize if I've glossed over something, but I can't find tests for editing channels, nor examples.

Adding tests for creating, editing channel permissions and then deleting said channel would be nice.

**Comment by 5HT2** [comment]
I eventually figured it out here, but I'm sure there has to be a cleaner way of doing it. 

https://github.com/kami-blue/bot-kt/blob/6b2342d/src/main/kotlin/commands/ArchiveCommand.kt

**Comment by Tea-Ayataka** [comment]
This library isn't documented yet at all. also, the tests needs to be well implemented.
Btw, There is an extension function that you can use to create a permissionset object.
[extensions.kt](https://github.com/Tea-Ayataka/Kordis/blob/development/src/main/kotlin/net/ayataka/kordis/entity/extensions.kt)
