### ISSUE TITLE
Option to download entire member list / check if you have intents 

### ISSUE THREAD

**Issue by 5HT2** [Tea-Ayataka/Kordis#14]
Hi, this commit (https://github.com/Tea-Ayataka/Kordis/commit/8d4d96f8759741e73febc18c7dd01043d6a7d4ef) removes the ability to get the entire member list. I understand this is a [Privileged Intent](https://discord.com/developers/docs/topics/gateway#privileged-intents), but your bot only requires verification for such permissions once it's inside more than 100 servers (and you also cannot apply until you have 75 servers). 

I didn't realize until now as I switched from using 0.2.3 to the latest commit as I saw it had newer API support. It would be nice to readd this functionality with a check for privileged intents.

**Comment by Tea-Ayataka** [comment]
Hi. I didn't mean to remove that function. Just had no time to implement it and wanted to push it to jitpack.

**Comment by 5HT2** [comment]
Thank you! That's good to hear, I was pretty confused.

**Comment by 5HT2** [comment]
Hi, would you mind reopening this if you haven't added this functionality yet?

**Comment by 5HT2** [comment]
Hi, this still hasn't been fixed. If you don't want to re-add that functionality in the future, I'd suggest labeling this issue, or reopening it if you're open to someone doing so.
